server:
  port: 8443
  servlet:
    session:
      timeout: 30
  ssl:
    key-store: classpath:cert/cert.pkcs12
    key-store-type: PKCS12
    key-store-password: "qwe123"

spring:
  data:
    mongodb:
      host: home.jowookjae.in
      database: finance
      auto-index-creation: true
      username: admin
      password: qwe123
  rabbitmq:
    host: home.jowookjae.in
    username: guest
    password: guest