server:
  port: 8080

spring:
  data:
    mongodb:
      host: home.jowookjae.in
      database: finance
      auto-index-creation: true
  rabbitmq:
    host: home.jowookjae.in
    username: guest
    password: guest