server:
  port: 8080

spring:
  data:
    mongodb:
      host: 218.147.138.41
      database: finance
      auto-index-creation: true

webdriver:
  chrome:
    remote:
      url: http://218.147.138.41:4444
