server:
  port: 8080
spring:
  data:
    mongodb:
      host: jowookjae.in
      database: finance
      auto-index-creation: true
      username: admin
      password: qwe123
  jackson:
    serialization:
      indent_output: true

logging:
  level:
    org:
      openqa:
        selenium:
          remote: warn
